name: weather_info
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^2.3.13
  http: ^0.13.4
  get_it: ^7.2.0
  stacked_services: ^0.9.3
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  stacked_generator:
  mockito: ^5.2.0
  flutter_launcher_icons: ^0.9.3
  json_serializable: ^6.3.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
